title: Matthew Lewton's Portfolio Website
email: mlewton@purdue.edu
description: > 
  Matthew Lewton's portfolio website built with Jeckyll to showcase 
  enineering, programming, and manufacturing projects.
url: mattlewton.me
#url: http://localhost:4000
github_username: matt-lewton9

imgPath: /assets/images/

collections:
 engineering:
  output: true
  order:
   - nasaMinds.md
   - DesktopCNC.md
 programming:
  output: true  
 manufacturing:
  output: true

exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- .gitignore
