title: Matthew Lewton's Portfolio Website
email: mlewton@purdue.edu
description: > 
  Matthew Lewton's portfolio website built with Jeckyll to showcase 
  enineering, programming, and manufacturing projects.

github_username: matt-lewton9

imgPath: assets/images/

collections:
 design:
  output: true
 programming:
  output: true  
 manufacturing:
  output: true   

exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- .gitignore
